-- MySQL Script generated by MySQL Workbench
-- 10/25/16 12:14:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CITLabMonitor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CITLabMonitor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CITLabMonitor` DEFAULT CHARACTER SET utf8 ;
USE `CITLabMonitor` ;

-- -----------------------------------------------------
-- Table `Major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Major` (
  `MajorId` INT NOT NULL AUTO_INCREMENT,
  `MajorName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`MajorId`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `MajorName_UNIQUE` ON `Major` (`MajorName` ASC);


-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student` (
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `LNumber` CHAR(9) NOT NULL,
  `Password` VARCHAR(16) NOT NULL,
  `StudentId` INT NOT NULL,
  `EMailAddress` VARCHAR(50) NULL,
  `MajorId` INT NOT NULL,
  PRIMARY KEY (`StudentId`),
  CONSTRAINT `Student_Major_FK`
    FOREIGN KEY (`MajorId`)
    REFERENCES `Major` (`MajorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `StudentId_UNIQUE` ON `Student` (`StudentId` ASC);

CREATE UNIQUE INDEX `EMailAddress_UNIQUE` ON `Student` (`EMailAddress` ASC);

CREATE UNIQUE INDEX `LNumber_UNIQUE` ON `Student` (`LNumber` ASC);

CREATE INDEX `Student_Major_FK_idx` ON `Student` (`MajorId` ASC);


-- -----------------------------------------------------
-- Table `Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Instructor` (
  `InstructorId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `EMailAddress` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`InstructorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Course` (
  `CourseNumber` VARCHAR(10) NOT NULL,
  `CourseName` VARCHAR(50) NOT NULL,
  `LeadInstructorId` INT NOT NULL,
  PRIMARY KEY (`CourseNumber`),
  CONSTRAINT `Course_Instructor_FK`
    FOREIGN KEY (`LeadInstructorId`)
    REFERENCES `Instructor` (`InstructorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `CourseName_UNIQUE` ON `Course` (`CourseName` ASC);

CREATE INDEX `Course_Instructor_FK_idx` ON `Course` (`LeadInstructorId` ASC);


-- -----------------------------------------------------
-- Table `Term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Term` (
  `TermId` INT NOT NULL,
  `TermName` VARCHAR(50) NOT NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`TermId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Section` (
  `SectionNumber` VARCHAR(5) NOT NULL,
  `TermID` INT NOT NULL,
  `Year` INT NOT NULL,
  `InstructorId` INT NOT NULL,
  `CourseNumber` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`SectionNumber`, `TermID`, `Year`),
  CONSTRAINT `Section_Term_FK`
    FOREIGN KEY (`TermID`)
    REFERENCES `Term` (`TermId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Section_Instructor_FK`
    FOREIGN KEY (`InstructorId`)
    REFERENCES `Instructor` (`InstructorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Section_Course_FK`
    FOREIGN KEY (`CourseNumber`)
    REFERENCES `Course` (`CourseNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Section_Term_FK_idx` ON `Section` (`TermID` ASC);

CREATE INDEX `Section_Instructor_FK_idx` ON `Section` (`InstructorId` ASC);

CREATE INDEX `Section_Course_FK_idx` ON `Section` (`CourseNumber` ASC);


-- -----------------------------------------------------
-- Table `StudentRegistration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentRegistration` (
  `StudentId` INT NOT NULL,
  `SectionNumber` VARCHAR(5) NOT NULL,
  `TermId` INT NOT NULL,
  `Year` INT NOT NULL,
  PRIMARY KEY (`StudentId`, `SectionNumber`, `TermId`, `Year`),
  CONSTRAINT `StudentRegistration_Student_FK`
    FOREIGN KEY (`StudentId`)
    REFERENCES `Student` (`StudentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StudentRegistration_Section_FK`
    FOREIGN KEY (`SectionNumber` , `TermId` , `Year`)
    REFERENCES `Section` (`SectionNumber` , `TermID` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `StudentRegistration_Section_FK_idx` ON `StudentRegistration` (`SectionNumber` ASC, `TermId` ASC, `Year` ASC);


-- -----------------------------------------------------
-- Table `Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Location` (
  `LocationId` INT NOT NULL AUTO_INCREMENT,
  `LocationName` VARCHAR(50) NOT NULL,
  `StationId` INT NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`LocationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Visit` (
  `VisitId` INT NOT NULL AUTO_INCREMENT,
  `StartTime` DATETIME NOT NULL,
  `EndTime` DATETIME NULL,
  `StudentId` INT NOT NULL,
  `LocationId` INT NOT NULL,
  PRIMARY KEY (`VisitId`),
  CONSTRAINT `Visit_Student_FK`
    FOREIGN KEY (`StudentId`)
    REFERENCES `Student` (`StudentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Visit_Location_FK`
    FOREIGN KEY (`LocationId`)
    REFERENCES `Location` (`LocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Visit_Student_FK_idx` ON `Visit` (`StudentId` ASC);

CREATE INDEX `Visit_Location_FK_idx` ON `Visit` (`LocationId` ASC);


-- -----------------------------------------------------
-- Table `Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task` (
  `TaskId` INT NOT NULL AUTO_INCREMENT,
  `VisitId` INT NOT NULL,
  `SectionNumber` VARCHAR(5) NULL,
  `BriefDescription` VARCHAR(50) NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `EndTime` DATETIME NULL,
  PRIMARY KEY (`TaskId`),
  CONSTRAINT `Task_Visit_FK`
    FOREIGN KEY (`VisitId`)
    REFERENCES `Visit` (`VisitId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Task_Section_FK`
    FOREIGN KEY (`SectionNumber`)
    REFERENCES `Section` (`SectionNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Task_Visit_FK_idx` ON `Task` (`VisitId` ASC);

CREATE INDEX `Task_Section_FK_idx` ON `Task` (`SectionNumber` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
